networks:
  default:
    driver: bridge

services: 
  api:
    build:
      context: ./api 
    container_name: "api"
    ports: 
      - "5000:5000"
    volumes: 
      - ./api/:/app
    env_file:
      - .env
    depends_on:
      - db

  data-loader:
    build:
      context: ./data_loader
    container_name: "data-loader"
    depends_on:
      - db
    volumes:
      - ./data_loader:/app
    env_file:
      - .env

  db:
    image: postgres
    container_name: "database_postgres"
    restart: always
    networks:
      - default
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    depends_on:
      - db
    restart: always
    networks:
      - default
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data: