version: '3'

networks:
  default:
    driver: bridge

services: 
  api:
    build: .
    container_name: "api"
    ports: 
      - "5000:5000"
    volumes: 
      - ./api/:/api
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    networks:
      - default
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    networks:
      - default
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data: